listener:
  port: "![r8eRSDnfz8I=]"
db:
  host: "![AKoBdRfoXs7DmExsVTM/Eg==]"
  port: "![lAbQHC8pUqE=]"
  user: "![qNsNvUUJQno=]"
  password: "![ok1xhEp02bQJRK4PhymlpQ==]"
  db: "![IPjQZtPQr+iRXvZNkVEMIw==]"