#%RAML 1.0
title: Mysql-db-pagination-sapi
version: v1
protocols: HTTPS
mediaType: application/json
description: Fetching all the employees records

traits:
  offset-limit: !include traits/offset-limitTrait.raml
  response: !include traits/responseTrait.raml
  basicAuth: !include traits/basicAuthenticationTrait.raml
types:
  success-200-response: !include dataTypes/success-200-DataType.raml
  error-400-response: !include dataTypes/error-400-DataType.raml
resourceTypes:
  fetchingEmployeeRecords: !include resourceTypes/employeeRecordsResourceType.raml

/employeeRecords:
  type:
    fetchingEmployeeRecords
